### PR TITLE
Add subset lock system for blender

### PR DESCRIPTION
**Pull request by Strangenoise**
This MR adds a system that adds lock subset in the db system.
Also adds working behaviour in Blender.
Here are some details:

Lock is removed when Blender is closed (using atexit lib)
Lock is invalid when flush delay is passed (defined in project's settings, necessary if blender crashes and can't unlock)
Lock is invalid when lock site is the same as user's local site

Implementation:

All the functional code was added to a lock.py file in openpype/pipeline.
An operator and a timer were added to the ops.py file in hosts/blender/api.

How to test:

Open a blender file from OpenPype
Once the scene is opened, close blender
Go onto another computer (see bellow if you can't switch computer) and open the same blender file from OpenPype
A popup should indicate you that the file is locked and that you can QUIT or PROCEED anyway

If you can't switch computer:
As the site is the same between the lock one and yours, the only solution is to edit hosts/blender/api/lock.py locked_on_same_site() and compare with anything but get_local_site_id().

### CODE REVIEW

**Comment by Tilix4** [comment]
Some code here seems to be related to the check workfile is up-to-date feature by @Sharkitty. Please clean your code hierarchy.

**Comment by Strangenoise** [comment]
> Some code here seems to be related to the check workfile is up-to-date feature by @Sharkitty. Please clean your code hierarchy.

Do you know on which branch Sharkitty has done the workfile is up-to-date feature ?  
I can't find it so I can't find on which branch I need to rebase (and perhaps edit this PR destination branch).

**Comment by Tilix4** [comment]
> > Some code here seems to be related to the check workfile is up-to-date feature by @Sharkitty. Please clean your code hierarchy.
> 
> Do you know on which branch Sharkitty has done the workfile is up-to-date feature ? I can't find it so I can't find on which branch I need to rebase (and perhaps edit this PR destination branch).

Everything is in the branches builder we had. The current code used in our OP is on `studio/feature/blender_workfile_out_of_date_handling` (gitlab).
I believe your feature has nothing to do with Hayley's work, and also the fact that your history has only one commit is very confusing, I don't know if it is how gitkraken works (if so, I think it's bad practice) or if it is mistake on your side when you moved code.

**Comment by Strangenoise** [comment]
For rebase reasons, this PR was closed.  
Use this one to check the feature: https://github.com/kaamaurice/OpenPype/pull/167

**Pull request closed without merging**
