### PR TITLE
Feature/remove and load

### PR DESCRIPTION
**Pull request by Sharkitty**
## Description
Added the ability to remove and load a container, as a way to reset it.
Also added `InventoryAction` plugins support for blender host.

## Testing notes:
- Merge or cherry-pick this into main production branch.
- Open any asset with containers in the manage.
- Right click on the container that should be reset and select `Extra actions` -> `Remove and load`.
Testing tip: As newly loaded subsets are placed at origin, moving the subset you want to rest before running the inventory action will provide a good visual feedback that the action worked.

### CODE REVIEW

**Comment by Tilix4** [comment]
Thanks! But IMO this belongs to our studio addon ATM. I recommend moving it there, what do you think?

**Comment by Sharkitty** [comment]
> Thanks! But IMO this belongs to our studio addon ATM. I recommend moving it there, what do you think?

I think this would be useful for anyone experiencing an issue with a container that needs to be reloaded. Perhaps not just our studio.

**Comment by Tilix4** [comment]
> > Thanks! But IMO this belongs to our studio addon ATM. I recommend moving it there, what do you think?
> 
> I think this would be useful for anyone experiencing an issue with a container that needs to be reloaded. Perhaps not just our studio.

Maybe, therefore, as it is not relevant at all with our current Blender refactor, it must be PRed against `develop` and not for Blender only but all hosts (moved to the main `plugins/inventory`)

**Comment by Sharkitty** [comment]
> > > Thanks! But IMO this belongs to our studio addon ATM. I recommend moving it there, what do you think?
> > 
> > 
> > I think this would be useful for anyone experiencing an issue with a container that needs to be reloaded. Perhaps not just our studio.
> 
> Maybe, therefore, as it is not relevant at all with our current Blender refactor, it must be PRed against `develop` and not for Blender only but all hosts (moved to the main `plugins/inventory`)

I made a PR to develop as requested: [PR 4930](https://github.com/ynput/OpenPype/pull/4930)

**Pull request closed without merging**
