### PR TITLE
Fix: Empty filepaths make remap fail

### PR DESCRIPTION
**Pull request by Tilix4**
## Changelog Description
Empty filepaths raises errors.

## Testing notes:
1. Load the prod test workfile you like
2. Create an empty text block in Blender's scripting
3. Publish workfile

### CODE REVIEW

**Comment by Sharkitty** [comment]
Empty texts are packed, I'm not sure how this test would make the publish fail.

**Comment by Tilix4** [comment]
> Empty texts are packed, I'm not sure how this test would make the publish fail.

In the subprocess they do because their `filepath == ""` and it tries to remap it when it couldn't.

**Comment by Sharkitty** [comment]
> > Empty texts are packed, I'm not sure how this test would make the publish fail.
> 
> In the subprocess they do because their `filepath == ""` and it tries to remap it when it couldn't.

I tried doing that on a branch that does not contain your changes, and I did not get any error.

**Comment by Tilix4** [comment]
> > > Empty texts are packed, I'm not sure how this test would make the publish fail.
> > 
> > 
> > In the subprocess they do because their `filepath == ""` and it tries to remap it when it couldn't.
> 
> I tried doing that on a branch that does not contain your changes, and I did not get any error.

Try to do it with e109 sh009 layout workfile

**Comment by Sharkitty** [comment]
> > > > Empty texts are packed, I'm not sure how this test would make the publish fail.
> > > 
> > > 
> > > In the subprocess they do because their `filepath == ""` and it tries to remap it when it couldn't.
> > 
> > 
> > I tried doing that on a branch that does not contain your changes, and I did not get any error.
> 
> Try to do it with e109 sh009 layout workfile

Still no fail for me

**Comment by Tilix4** [comment]
Have you fake usered the text file?

**Comment by Sharkitty** [comment]
> Have you fake usered the text file?

I just create it, and publish it, nothing else.

**Comment by Tilix4** [comment]
> > Have you fake usered the text file?
> 
> I just create it, and publish it, nothing else.

Okay I don't get how to reproduce it on your side. Maybe try to add some content to the text file and fake user it. But if you cannot and the code is okay to you, never mind...

**Review by Sharkitty — APPROVED** [review]
Code looks good, too bad I can't reproduce the original issue. I guess my distro just works too well :sunglasses:

**Pull request merged**
